import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { z } from "zod";
import type { PromptAsset } from "../../core/promptTypes";

/**
 * Reverse decomposition of an ALREADY-WRITTEN chapter.
 *
 * Goal: reconstruct the chapter's internal planning artifacts (a 6-section task
 * sheet + 3-8 scene cards) from the finished prose and the novel's book analysis,
 * which serves as EVIDENCE of the author's intent. The beat/章法 insight is
 * captured as a short `beatNote` so the caller can append it to the persisted
 * task sheet without writing a risky volume-level beat sheet.
 *
 * Scope note (see the consuming service): this prompt intentionally does NOT
 * produce a volume beat sheet. The beat sheet is volume-level and regenerated by
 * the existing volume beat-sheet generator; capturing a lightweight 章法定位 line
 * in the task sheet honors the intent without touching volume state.
 */

export interface ReverseDecomposeChapterInput {
  chapterTitle: string;
  chapterContent: string;
  analysisEvidence: string;
  targetWordCount?: number;
}

const reverseDecomposeSceneCardSchema = z.object({
  key: z.string().trim().min(1).max(48).optional(),
  title: z.string().trim().min(1).max(64),
  purpose: z.string().trim().min(1),
  mustAdvance: z.array(z.string().trim().min(1).max(160)).max(8).default([]),
  mustPreserve: z.array(z.string().trim().min(1).max(160)).max(8).default([]),
  entryState: z.string().trim().min(1),
  exitState: z.string().trim().min(1),
  forbiddenExpansion: z.array(z.string().trim().min(1).max(160)).max(8).default([]),
  targetWordCount: z.number().int().positive(),
  resistance: z.string().trim().max(240).optional().default(""),
  turn: z.string().trim().max(240).optional().default(""),
  emotionalShift: z.string().trim().max(240).optional().default(""),
  readerValue: z.string().trim().max(240).optional().default(""),
});

/**
 * Relaxed scene-plan shape for the LLM output. It deliberately omits the brittle
 * `lengthBudget` and `readerExperience` sub-objects; the consuming service
 * completes those before serializing via `serializeChapterScenePlan`. This keeps
 * the generation contract robust while still reconstructing a plan that matches
 * the planner-produced `ChapterScenePlan`.
 */
export const reverseDecomposeScenePlanSchema = z.object({
  targetWordCount: z.number().int().positive(),
  scenes: z.array(reverseDecomposeSceneCardSchema).min(3).max(8),
});

export const reverseDecomposeChapterSchema = z.object({
  taskSheet: z.string().trim().min(1).max(600),
  scenePlan: reverseDecomposeScenePlanSchema,
  beatNote: z.string().trim().max(120).optional(),
});

export const reverseDecomposeChapterPrompt: PromptAsset<
  ReverseDecomposeChapterInput,
  z.infer<typeof reverseDecomposeChapterSchema>
> = {
  id: "novel.reverse_decompose_chapter",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 14000,
    requiredGroups: [],
    preferredGroups: [],
  },
  outputSchema: reverseDecomposeChapterSchema,
  structuredOutputHint: {
    mode: "auto",
    note: "任务单严格 ≤600 字，必须包含六个板块：章节目标 / 关键角色 / 必须推进 / 必须保留 / 风险提醒 / 收尾钩子。scenePlan 必须包含 3-8 张场景卡，每张卡 entryState 与上一章 exitState 顺接。beatNote 用一句话说明本章承担的叙事节拍/章法（例如“中段压力升级”或“关系转折”），不要超过 40 字。",
    example: {
      taskSheet:
        "章节目标：揭露主角身世并提供关键线索。\n关键角色：主角、老仆。\n必须推进：身世真相、逃亡计划。\n必须保留：玉佩信物、旧宅谜团。\n风险提醒：避免过早揭穿反派。\n收尾钩子：老仆临终吐露第二个名字。",
      scenePlan: {
        targetWordCount: 2200,
        scenes: [
          {
            title: "旧宅对峙",
            purpose: "主角与老仆对峙，逼问身世。",
            mustAdvance: ["身世真相浮出水面"],
            mustPreserve: ["玉佩信物"],
            entryState: "主角回到旧宅，心绪不宁。",
            exitState: "老仆承认隐藏了二十年。",
            forbiddenExpansion: ["直接揭穿反派身份"],
            targetWordCount: 900,
            resistance: "老仆本能回避。",
            turn: "老仆从否认转为松口。",
            emotionalShift: "主角由愤怒转为震惊。",
            readerValue: "满足对身世的代偿性好奇。",
          },
          {
            title: "临终吐露",
            purpose: "老仆临终说出第二个名字。",
            mustAdvance: ["逃亡计划启动"],
            mustPreserve: ["旧宅谜团"],
            entryState: "老仆承认隐藏了二十年。",
            exitState: "主角带着第二个名字连夜出逃。",
            forbiddenExpansion: ["展开追兵大战"],
            targetWordCount: 1300,
            resistance: "老仆体力不支。",
            turn: "临终前吐露关键线索。",
            emotionalShift: "悬念升级，命运被改写。",
            readerValue: "抛出下一段追读钩子。",
          },
        ],
      },
      beatNote: "中段压力升级与关系转折",
    },
  },
  render: (input, context) => [
    new SystemMessage([
      "你是一位长篇小说写作导演，擅长从已完成的章节正文中反推作者原本的内部规划。",
      "你的任务不是改写正文，也不是扩写，而是基于【已写完的章节正文】与【本书拆书证据】，重建这一章的“任务单”与“场景卡”，并点明它承担的叙事节拍（章法）。",
      "",
      "【输入】",
      "1. 章节标题（可能是“第N章”之类的占位）。",
      "2. 本章已写完的正文（这是事实依据，必须忠实于它）。",
      "3. 本书拆书证据（plot_structure / timeline / character_system / worldbuilding 等），用于判断角色、世界与时间线的一致性。",
      "",
      "【输出要求】",
      "只输出严格 JSON，不要输出 Markdown、解释、注释或额外文本。",
      "必须包含三个字段：taskSheet（字符串）、scenePlan（对象）、beatNote（可选字符串）。",
      "",
      "【任务单 taskSheet】",
      "1. 严格 ≤600 字（含换行）。",
      "2. 必须按以下六个板块书写，板块名固定为：章节目标、关键角色、必须推进、必须保留、风险提醒、收尾钩子。",
      "3. 章节目标：本章最核心要推进的事。",
      "4. 关键角色：本章实际出场的少量关键人物。",
      "5. 必须推进：本章必须兑现的 2-4 条具体进展（短句、可执行）。",
      "6. 必须保留：本章不能丢失的伏笔/道具/悬念。",
      "7. 风险提醒：本章最容易写歪或写空的风险点。",
      "8. 收尾钩子：本章结尾把读者推向的新关注点。",
      "",
      "【场景卡 scenePlan】",
      "1. 必须包含 3-8 张场景卡，每张卡的 entryState 必须顺接上一章的 exitState（首张顺接章节入口状态）。",
      "2. 每张卡需包含：title、purpose、mustAdvance（数组）、mustPreserve（数组）、entryState、exitState、forbiddenExpansion（数组）、targetWordCount（正整数）、resistance、turn、emotionalShift、readerValue。",
      "3. targetWordCount 为各场景的目标字数，所有场景 targetWordCount 之和约等于本章总篇幅；不要出现 0 或负数。",
      "4. 场景卡之间必须形成清晰的因果/情绪递进，禁止彼此孤立。",
      "",
      "【章法 beatNote】",
      "1. 可选字段。用一句话（≤40 字）说明本章承担的叙事节拍或章法位置，例如“中段压力升级”“关系转折”“悬念回收”。",
      "2. 不要写成长段落，不要重复任务单内容。",
      "",
      "【忠于正文】",
      "所有重建内容必须能从正文中找到依据，不得凭空捏造未发生的情节；若正文信息不足，按保守、可继续推进的方式补全。",
    ].join("\n")),
    new HumanMessage([
      "请基于以下上下文，反推本章内部规划。",
      "",
      "【章节标题】",
      input.chapterTitle || "未命名章节",
      input.targetWordCount && Number.isFinite(input.targetWordCount) && input.targetWordCount > 0
        ? `\n【建议目标字数】\n${Math.round(input.targetWordCount)}`
        : "",
      "",
      "【已写完的章节正文】",
      input.chapterContent && input.chapterContent.trim()
        ? input.chapterContent
        : "（正文为空，仅依据标题与拆书证据保守重建）",
      "",
      "【本书拆书证据】",
      input.analysisEvidence && input.analysisEvidence.trim()
        ? input.analysisEvidence
        : "（无拆书证据）",
      "",
      "【输出要求】",
      "- 只输出严格 JSON",
      '- 结构：{"taskSheet":"...","scenePlan":{"targetWordCount":N,"scenes":[...]},"beatNote":"..."}',
      "- taskSheet 严格 ≤600 字并包含六个固定板块",
      "- scenePlan 含 3-8 张顺接的场景卡",
      "- 优先保证忠于正文、可执行、可继续推进",
    ].join("\n")),
  ],
};
